### ISSUE TITLE
pip3 install does not install katcp module

### ISSUE THREAD

**Issue by chultquist** [bmerry/ntsh#1]
Running "pip3 install ." on Mac OS (with Python3 installed using Homebrew) succeeds but does not install the katcp module, which leads to ntsh breaking:

hydra:ntsh carl$ pip3 install .
Processing /Users/carl/src/ntsh
Collecting prompt_toolkit (from ntsh==0.1)
  Downloading prompt_toolkit-1.0.14-py3-none-any.whl (248kB)
    100% |████████████████████████████████| 256kB 977kB/s 
Collecting pygments (from ntsh==0.1)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 334kB/s 
Collecting wcwidth (from prompt_toolkit->ntsh==0.1)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt_toolkit->ntsh==0.1)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: wcwidth, six, prompt-toolkit, pygments, ntsh
  Running setup.py install for ntsh ... done
Successfully installed ntsh-0.1 prompt-toolkit-1.0.14 pygments-2.2.0 six-1.10.0 wcwidth-0.1.7

hydra:ntsh carl$ ntsh
Traceback (most recent call last):
  File "/usr/local/bin/ntsh", line 11, in <module>
    load_entry_point('ntsh==0.1', 'console_scripts', 'ntsh')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/ntsh/main.py", line 27, in <module>
    from . import protocols, katcp
ImportError: cannot import name 'katcp'

hydra:ntsh carl$ ls /usr/local/lib/python3.6/site-packages/ntsh/
__init__.py	__pycache__	main.py		protocols.py

**Comment by bmerry** [comment]
Should be fixed by the latest commit.
